server:
  port: 7001


eureka:
  instance:
    hostname: localhost
  client:
    # 是否向注册中心注册本身服务
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://a.eureka.tt:${server.port}/eureka/